version: "3.9"

services:
  s3app:
    image: nginx:alpine
    container_name: 68-s3-app
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    networks:
      - backend
    read_only: true

networks:
  backend:
    driver: bridge
